### ISSUE TITLE
Small typos and thoughts

### ISSUE THREAD

**Issue by obDann** [nxskok/pasias#2]
Hi Professor. I hope all is well.

Firstly, I would like to say that I absolutely loved how the Applied Statistics Program was implemented; I found myself being quite happy when I got the opportunity to collaborate with others outside of my specialist-program while building my foundations in statistics. I personally found that the tools that I learned throughout C32 and D29 is going to be instrumental in my career, and I cannot thank you enough.

While I was in your course, I appreciate your time and effort for generating course materials as it is clear that passion and dedication went into it. With that being said, one factor I would have to attribute to my gradual improvement was definitely PASIAS. Now that I finally found the time, I figured that it may be best to improve PASIAS as it may help prospective Applied Statistics students (and that it was requested in the introduction of PASIAS).

There are a few things I caught while I went through it throughout the term, but I admittedly have to say that there are some weeks where I glimpsed at PASIAS, and did not necessarily go into depth (so unfortunately, I may not have caught all "issues" for the D29 content). At the same time, what I caught was a tad picky, so please take the feedback below with a grain of salt.

### Typos
Any items that are said verbatim from PASIAS will be wrapped in back quotes:

* In [16-4e](http://ritsokiguess.site/pasias/logistic-regression.html#what-makes-an-animal-get-infected) a parenthesis was missing `(in this kind of model, whether they're positive or negative...`
* [17-5d](http://ritsokiguess.site/pasias/logistic-regression-with-ordinal-or-nominal-response.html#alligator-food) `How you account for having Frequency as well?` I was not too sure what the question was trying to convey unless I went through the answer of the question
* The intended fivethirtyeight link in [17-8](http://ritsokiguess.site/pasias/logistic-regression-with-ordinal-or-nominal-response.html#how-do-you-like-your-steak) cannot be accessed
* [21-1f](http://ritsokiguess.site/pasias/repeated-measures.html#effect-of-drug-on-rat-weight) `To set that up, use gather as in the lecture notes to create one column of weights and and second column of times...` More specifically, `and and`
* [22-2e](http://ritsokiguess.site/pasias/discriminant-analysis.html#urine-and-obesity-what-makes-a-difference) `and thus how the groups differ in terms of the original variables.` \*at the time of writing this, a circle with two orthogonal lines intersecting in the middle of the circle\* `, but not much of anything else.` I was caught off guard with this
* [23-1](http://ritsokiguess.site/pasias/cluster-analysis.html#dissimilarities-between-fruits) Both Monty Python links got copyrighted and blocked the video :(
* [23-4h](http://ritsokiguess.site/pasias/cluster-analysis.html#sites-on-the-sea-bed) `Add a column to the original data that you read in in part (here) containing those cluster memberships, . Obtain a plot...` More specifically, `in in` and `cluster memberships, . `

### Comments on content from a student perspective
* What I love about the C32 and D29 assignments is that it is easy to start off and it is not as overwhelming. However, I personally had difficulty trying to start Chapter 23, since [Chapter 23-1](http://ritsokiguess.site/pasias/cluster-analysis.html#dissimilarities-between-fruits) starts off with data we had to clean. I understand "in the real world" that we have to do this as a first step (as almost all given data from an organization is never as neat as what you give us), but I typically use the first question to get the flow of the taught concept. However, this is more of a "me" thing.
* When I ran through [Chapter 26-1](http://ritsokiguess.site/pasias/frequency-table-analysis.html#college-plans) I found that `step` for backwards elimination worked for me at the time. Just proposing an alternative solution.
* This is more of a user story, but whenever a sub question is referenced (e.g. 18.2h references [18.1i](http://ritsokiguess.site/pasias/survival-analysis.html#part:posneg)), I have to typically open a tab for the reference. It would be nice to have a "go back to the question I was on" button, but I would imagine that this is a bit of a hassle to implement.

### Comments on branching
Though I am a bit hypocritical of not doing this for the majority of my repositories, have you considered exploring the concept of branching? I believe it would be beneficial in situations like:
* if you have more people involved in this repository, those people can branch out and add to your repository independently (but of course, you have to talk to them if there is ever a merge conflict)
* if you want to add a chapter/module, but you are not entirely complete and you do not want it publicly live (i.e. it is not shown on the actual site), but you do want to save it onto git.

Though these are a couple of ideas, I believe that branching could help this repository in the long run.

**Comment by nxskok** [comment]
16-4e fixed
17-5e this was that business of having each row of the data file represent one or more than one observation (after tidying). I'll clarify the question to make it clear that this is the issue here.
21-1f: should be "and a", corrected.
22-2e: there was a problem with a footnote here, which meant that what you saw is not how it was supposed to come out. Fixing.
23-1: YouTube has other links...
23-4h: "in in" and "cluster memberships" are actually both correct (or at least what I meant). I've added some commas to make things a bit clearer. By "cluster memberships" I mean "which cluster each observation is classified into". 

I take your point about looking for the first question to be a straightforward example of the technique, and 23.1 isn't. Maybe I can shuffle the questions around so that this one comes up a bit later. I don't really have a completely clear one, but the sites on the sea bed is the clearest of these. This is now the first one.

26.1 could indeed be done via step. I didn't suggest that as a solution because I wanted it to be clear what was being done: removing up-for-grabs things one at a time until everything left is significant. Step disguises this a bit to my mind. (My preference, at least to start with, is to use simple tools that show what is going on, even if there is a more efficient way that can be learned about later. Step uses drop1, so it should do the right thing here. It uses AIC rather than tests, so the final model might include something that could be excluded.)

The way the links to other questions are organized, it doesn't remember where you came from, so I think you are stuck with using the back button, or right clicking to open things in new tabs.

I will definitely look into the idea of branching -- thanks for the suggestion. I will in fact have some new chapters to add this summer, so this is a way of implementing it until I have everything in place.

Thanks for taking the time to pass on your comments. I appreciate it!

**Comment by nxskok** [comment]
I think the corrected version is now up. (The pdf still needs some work.)

**Comment by obDann** [comment]
Looks great professor! No arguments from my end with the changes. I will leave you the pleasure of closing this issue.

If you have not already looked at branching, here's something that can help you get started:
`[master] $ git branch <YOUR BRANCH NAME>  # create a branch in your local repository`
`[master] $ git branch -a  # look at all branches in your local repository`

Once you make a local branch, it's not on git just yet:
`[master] $ git push --set-upstream origin <YOUR BRANCH NAME>  # put the local branch onto github`
`[master] $ git checkout <YOUR BRANCH NAME>  # go into a branch`
`[<YOUR BRANCH NAME>] $`

From here, it is assumed that you do a series of commits in the branch you created until you are comfortable and ready to put any changes into the `master` branch. Any commits that are not the default/`master` branch are not placed in your product until you merge the branch onto `master`. 

With what I was taught, I would recommend having a `dev-branch` and then merging branches onto the `dev-branch` first before merging branches straight to `master`. That way, you can settle all your merge conflicts in `dev-branch` instead of `master` so that any errors won't show up on your live product.

`[dev-branch] $ git merge <YOUR BRANCH NAME>  # after this, you solve any conflicts, and then push`
`[dev-branch] $ git checkout master`
`[master] $ git merge dev-branch`

Hope this helps!
